Switch to libtirpc and support IPv6
unfs3/unfs3 pull request #20
Opened 2021-11-09 15:30 UTC by skoudmar

I have tested the pull request #17 and fixed and extended some of its functionality.

Works when connecting from both IPv4 and IPv6 clients.

Resolves:
#12, #13 

Helped by: @wentasah

2021-11-22 13:38 UTC, CendioOssman commented
Thanks for testing!

Which of these are bug fixes for #17? I'd prefer to get that fully fixed and merged first, before looking at further improvements..

2021-11-23 17:36 UTC, skoudmar commented
Commit f7acfc5 adds option `-4` which allowed me to find bugs related to starting unfsd on systems with IPv6 disabled (improvement). But the commit also fixes bug: Starting unfsd without specifying `-l <addr>` would crash on such systems.

Other commits are pure bug fixes.

2022-01-27 13:49 UTC, CendioOssman requested changes
I've incorporated the fixes in to my PR now. Thanks.

What remains here is the `-4` flag, and the portmap stuff, which I'm a bit unclear about.

2022-01-29 15:38 UTC, skoudmar commented on daemon.c
> +	}
I don't see this done implicitly.

It adds mappings required if we want to connect using IPv6 address.

Example mounting command:
```
mount [::1]:/exported /mnt
```

Without the mapping the command fails with:
```
mount.nfs: requested NFS version or transport protocol is not supported
```

2022-05-12 07:30 UTC, CendioOssman commented on daemon.c
> +	}
Sorry for the long delay replying.

I redid the tests, and could no longer get it working. So I'm not sure what I did last time...

Your suggestion is entirely correct. However, it highlighted that `svc_register()` was a legacy interface, so I went a bit further in e02a907b8b4d431e68aebe6602aa3690cce525da and fe3210b67f18e231c18cda77637689e5979019d5.

2022-05-12 07:35 UTC, closed without merging

2022-05-12 07:36 UTC, CendioOssman commented
I've merged #17 now, and all your fixes should hopefully be included.

Do you think you could do a test as well to make sure something isn't missing?

2022-05-12 15:45 UTC, skoudmar commented
Unfortunately, the functions svc_dg_create and svc_vc_create have different requirements on the state of the socket. More info and fix is in commit skoudmar/unfs3@a7bd4ba0c228cca1dbc78b8bf4699107a3542eaa.

2022-05-13 05:57 UTC, CendioOssman commented
Crap. You're right. I missed that case. Thanks for the fix! It's on `master` now.